---
title: "CV"
---

::: {style="text-align: center; margin-bottom: 20px;"}
<a href="https://www.linkedin.com/in/louiewee/" target="_blank" style="margin-right: 15px;"> <i class="fab fa-linkedin" style="font-size: 24px;"></i> LinkedIn </a> <a href="https://github.com/louiewee" target="_blank" style="margin-right: 15px;"> <i class="fab fa-github" style="font-size: 24px;"></i> GitHub </a> <a href="mailto:louieywee@gmail.com" style="margin-right: 15px;"> <i class="fas fa-envelope" style="font-size: 24px;"></i> Email </a>
:::

## Professional Experience

**Northern Energy Innovation** - Student Research Assistant\
*Whitehorse, Yukon\
May 2024 - Aug 2024*

-   Supported analytics for renewable integration in remote Northern Canadian power systems
-   Conducted in-depth exploratory data analysis on structured datasets consisting of simulated scenarios resulting from the installation of a wind turbine and battery energy storage system to the existing power system
-   Forecasted variability in remote community energy data by applying statistical methods such as block-based bootstrapping
-   Delivered reproducible code in R, Python and MATLAB for internal use and documentation of data workflows

**CTS Global Equity Group** - Research Officer\
*Manila, Philippines\
Nov 2015 - Jan 2021*

-   Gathered macroeconomic and stock-specific information to seek and capitalize on immediate trading opportunities primarily in the Hong Kong equities market
-   Conducted weekly presentations on the Hong Kong market to the trading team and investment team, highlighting stocks in play, notable events, and brief market recaps
-   Semi-automated Microsoft Excel spreadsheets with Bloomberg API to efficiently extract relevant data for quantitative and qualitative analyses
-   Team of the Year 2018: Recognized for valuable contributions to team success
-   Extra Mile Award: For going above and beyond expected duties and responsibilities

## Other Experience (Volunteer/Part-Time)

**Filipino Tech Professionals of Calgary (FTP-YYC)** - Social Media & Communications Lead\
*Calgary, Alberta\
Sep 2025 - Present*

**Platform Calgary** - Volunteer\
*Calgary, Alberta\
June 2025 - Present*\

-   QAI Ventures x GenQ Global Hackathon 2025
-   IMPACT 2025 Summit
-   NEON MOON: Avatar Innovations' Energy Innovation Corridor Stampede Party 2025
-   Community Connect (June 2025)

**Rodd & Gunn** - Sales Associate\
*Kelowna, British Columbia\
Nov 2023 - Apr 2024*

**Okanagan College** - 2024 Careers Expo & Employment Fair Volunteer\
*Kelowna, British Columbia\
Feb 7, 2024*

**JW Marriott Nashville** - Banquet Cook\
*Nashville, Tennessee\
Apr 2022 - Mar 2023*

## Education

**Post-Baccalaureate Diploma in Marketing & Data Analytics**\
*Okanagan College*

-   GPA: 95%
-   Okanagan College Academic Achievement Scholarship Award recipient
-   Awarded Dean's List for all semesters

**Bachelor's Degree in Economics**\
*University of the Philippines*

-   Graduated with Cum Laude distinction
-   Awarded College Scholar for all semesters

## Skills

**Data Analysis**: Python, R, SQL, Excel, SPSS, MATLAB, Bloomberg

**Data Visualization**: Tableau, Power BI

**Cloud Computing & Database Management**: Azure, Snowflake, Databricks

**Web Development**: HTML, CSS

## Certificates

**CFA Institute**

-   CFA Program Level I [{{< fa link >}}](https://credentials.cfainstitute.org/78516e56-9670-41fb-9ac7-31cf6ef57e2d#acc.N4SqtiRo)

**Canadian Securities Institute (CSI)**

-   Investment Management Techniques (IMT®)
-   Canadian Securities Course (CSC®) [{{< fa link >}}](https://www.credly.com/badges/82cd72aa-1198-4315-9aca-80b8d2dcb1ee/public_url)
-   Investment Funds in Canada (IFC) [{{< fa link >}}](https://www.credly.com/badges/7bbb98eb-e4ce-4d7c-ba3a-f0caee954e01/public_url)

**Microsoft**

-   Azure Fundamentals (AZ-900) [{{< fa link >}}](https://learn.microsoft.com/en-us/users/louiechristopherwee-2936/credentials/786c83f9160c2bd6?ref=https%3A%2F%2Fwww.linkedin.com%2F)

**Panel on Research Ethics -** Tri-Council Policy Statement: Ethical Conduct for Research Involving Humans (TCPS 2: Core 2022) [{{< fa link >}}](https://drive.google.com/file/d/1xDqjBB1wbKPzG5-LUWeKv4BF8_RWbSZW/view)

**Google**

-   Google Analytics [{{< fa link >}}](https://skillshop.credential.net/208ea7f1-85a1-4757-ae42-a9b81d2fd686#acc.lpnKWNyO)
-   Data Analytics Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/CYKLBEMMR2EH)

**freeCodeCamp**

-   Data Analysis with Python [{{< fa link >}}](https://www.freecodecamp.org/certification/chairmanwee/data-analysis-with-python-v7)
-   College Algebra with Python [{{< fa link >}}](https://www.freecodecamp.org/certification/chairmanwee/college-algebra-with-python-v8)
-   Scientific Computing with Python [{{< fa link >}}](https://www.freecodecamp.org/certification/chairmanwee/scientific-computing-with-python-v7)

**DeepLearning.AI**

-   Generative Adversarial Networks (GANS) Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/Y6RANZ4J64U3)
-   Natural Language Processing Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/8RU8TH7R9FWV)
-   AI for Good Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/KKQBA8JKLN7H)
-   Deep Learning Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/UTH7CCQMCNFC)
-   TensorFlow Developer Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/9L4LGEM2N2LP)
-   Machine Learning Specialization [{{< fa link >}}](https://www.coursera.org/account/accomplishments/specialization/certificate/2BUJW9KLJEM5)

**Culinary Solutions Australia -** Certificate III in Commercial Cookery

**International School for Culinary Arts and Hotel Management (ISCAHM)** - Diploma in Culinary Arts and Kitchen Management

## Languages

**English**: Fluent

-   CELPIP-General: CLB 12 [{{< fa link >}}](https://www.celpip.ca/prepare-for-celpip/score-comparison-chart-2/#anchor-3)

**French**: Intermediate

-   TCF Canada: NCLC 8

**Tagalog**: Native

## Test Scores

**Okanagan College Typing Test**: 93 words per minute
